package ch1mp.bahdulator.protocols.fields;

import ch1mp.bahdulator.protocols.ProtocolField;
import ch1mp.bahdulator.protocols.Value;

public class TCPOptionKinds extends ProtocolField {

    public TCPOptionKinds(){
        super("tcp.option_kinds");
        super.addValue(0, new Value("End of Option List", ""));
        super.addValue(1, new Value("No-Operation", ""));
        super.addValue(2, new Value("Maximum Segment Size", ""));
        super.addValue(3, new Value("Window Scale", ""));
        super.addValue(4, new Value("SACK Permitted", ""));
        super.addValue(5, new Value("SACK", ""));
        super.addValue(6, new Value("Echo (obsoleted by option 8)", ""));
        super.addValue(7, new Value("Echo Reply (obsoleted by option 8)", ""));
        super.addValue(8, new Value("Timestamps", ""));
        super.addValue(9, new Value("Partial Order Connection Permitted (obsolete)", ""));
        super.addValue(10, new Value("Partial Order Service Profile (obsolete)", ""));
        super.addValue(11, new Value("CC (obsolete)", ""));
        super.addValue(12, new Value("CC.NEW (obsolete)", ""));
        super.addValue(13, new Value("CC.ECHO (obsolete)", ""));
        super.addValue(14, new Value("TCP Alternate Checksum Request (obsolete)", ""));
        super.addValue(15, new Value("TCP Alternate Checksum Data (obsolete)", ""));
        super.addValue(16, new Value("Skeeter", ""));
        super.addValue(17, new Value("Bubba", ""));
        super.addValue(18, new Value("Trailer Checksum Option", ""));
        super.addValue(19, new Value("MD5 Signature Option (obsoleted by option 29)", ""));
        super.addValue(20, new Value("SCPS Capabilities", ""));
        super.addValue(21, new Value("Selective Negative Acknowledgements", ""));
        super.addValue(22, new Value("Record Boundaries", ""));
        super.addValue(23, new Value("Corruption experienced", ""));
        super.addValue(24, new Value("SNAP", ""));
        super.addValue(25, new Value("Unassigned (released 2000-12-18)", ""));
        super.addValue(26, new Value("TCP Compression Filter", ""));
        super.addValue(27, new Value("Quick-Start Response", ""));
        super.addValue(28, new Value("User Timeout Option (also", ""));
        super.addValue(29, new Value("TCP Authentication Option (TCP-AO)", ""));
        super.addValue(30, new Value("Multipath TCP (MPTCP)", ""));
        super.addValue(31, new Value("Reserved (known unauthorized use without proper IANA assignment) [**]", ""));
        super.addValue(32, new Value("Reserved (known unauthorized use without proper IANA assignment) [**]", ""));
        super.addValue(33, new Value("Reserved (known unauthorized use without proper IANA assignment) [**]", ""));
        super.addValue(34, new Value("TCP Fast Open Cookie", ""));
        super.addValue(35, new Value("Reserved", ""));
        super.addValue(36, new Value("Reserved", ""));
        super.addValue(37, new Value("Reserved", ""));
        super.addValue(38, new Value("Reserved", ""));
        super.addValue(39, new Value("Reserved", ""));
        super.addValue(40, new Value("Reserved", ""));
        super.addValue(41, new Value("Reserved", ""));
        super.addValue(42, new Value("Reserved", ""));
        super.addValue(43, new Value("Reserved", ""));
        super.addValue(44, new Value("Reserved", ""));
        super.addValue(45, new Value("Reserved", ""));
        super.addValue(46, new Value("Reserved", ""));
        super.addValue(47, new Value("Reserved", ""));
        super.addValue(48, new Value("Reserved", ""));
        super.addValue(49, new Value("Reserved", ""));
        super.addValue(50, new Value("Reserved", ""));
        super.addValue(51, new Value("Reserved", ""));
        super.addValue(52, new Value("Reserved", ""));
        super.addValue(53, new Value("Reserved", ""));
        super.addValue(54, new Value("Reserved", ""));
        super.addValue(55, new Value("Reserved", ""));
        super.addValue(56, new Value("Reserved", ""));
        super.addValue(57, new Value("Reserved", ""));
        super.addValue(58, new Value("Reserved", ""));
        super.addValue(59, new Value("Reserved", ""));
        super.addValue(60, new Value("Reserved", ""));
        super.addValue(61, new Value("Reserved", ""));
        super.addValue(62, new Value("Reserved", ""));
        super.addValue(63, new Value("Reserved", ""));
        super.addValue(64, new Value("Reserved", ""));
        super.addValue(65, new Value("Reserved", ""));
        super.addValue(66, new Value("Reserved", ""));
        super.addValue(67, new Value("Reserved", ""));
        super.addValue(68, new Value("Reserved", ""));
        super.addValue(69, new Value("Encryption Negotiation (TCP-ENO)", ""));
        super.addValue(70, new Value("Reserved (known unauthorized use without proper IANA assignment) [**]", ""));
        super.addValue(71, new Value("Reserved", ""));
        super.addValue(72, new Value("Reserved", ""));
        super.addValue(73, new Value("Reserved", ""));
        super.addValue(74, new Value("Reserved", ""));
        super.addValue(75, new Value("Reserved", ""));
        super.addValue(76, new Value("Reserved (known unauthorized use without proper IANA assignment) [**]", ""));
        super.addValue(77, new Value("Reserved (known unauthorized use without proper IANA assignment) [**]", ""));
        super.addValue(78, new Value("Reserved (known unauthorized use without proper IANA assignment) [**]", ""));
        super.addValue(79, new Value("Reserved", ""));
        super.addValue(80, new Value("Reserved", ""));
        super.addValue(81, new Value("Reserved", ""));
        super.addValue(82, new Value("Reserved", ""));
        super.addValue(83, new Value("Reserved", ""));
        super.addValue(84, new Value("Reserved", ""));
        super.addValue(85, new Value("Reserved", ""));
        super.addValue(86, new Value("Reserved", ""));
        super.addValue(87, new Value("Reserved", ""));
        super.addValue(88, new Value("Reserved", ""));
        super.addValue(89, new Value("Reserved", ""));
        super.addValue(90, new Value("Reserved", ""));
        super.addValue(91, new Value("Reserved", ""));
        super.addValue(92, new Value("Reserved", ""));
        super.addValue(93, new Value("Reserved", ""));
        super.addValue(94, new Value("Reserved", ""));
        super.addValue(95, new Value("Reserved", ""));
        super.addValue(96, new Value("Reserved", ""));
        super.addValue(97, new Value("Reserved", ""));
        super.addValue(98, new Value("Reserved", ""));
        super.addValue(99, new Value("Reserved", ""));
        super.addValue(100, new Value("Reserved", ""));
        super.addValue(101, new Value("Reserved", ""));
        super.addValue(102, new Value("Reserved", ""));
        super.addValue(103, new Value("Reserved", ""));
        super.addValue(104, new Value("Reserved", ""));
        super.addValue(105, new Value("Reserved", ""));
        super.addValue(106, new Value("Reserved", ""));
        super.addValue(107, new Value("Reserved", ""));
        super.addValue(108, new Value("Reserved", ""));
        super.addValue(109, new Value("Reserved", ""));
        super.addValue(110, new Value("Reserved", ""));
        super.addValue(111, new Value("Reserved", ""));
        super.addValue(112, new Value("Reserved", ""));
        super.addValue(113, new Value("Reserved", ""));
        super.addValue(114, new Value("Reserved", ""));
        super.addValue(115, new Value("Reserved", ""));
        super.addValue(116, new Value("Reserved", ""));
        super.addValue(117, new Value("Reserved", ""));
        super.addValue(118, new Value("Reserved", ""));
        super.addValue(119, new Value("Reserved", ""));
        super.addValue(120, new Value("Reserved", ""));
        super.addValue(121, new Value("Reserved", ""));
        super.addValue(122, new Value("Reserved", ""));
        super.addValue(123, new Value("Reserved", ""));
        super.addValue(124, new Value("Reserved", ""));
        super.addValue(125, new Value("Reserved", ""));
        super.addValue(126, new Value("Reserved", ""));
        super.addValue(127, new Value("Reserved", ""));
        super.addValue(128, new Value("Reserved", ""));
        super.addValue(129, new Value("Reserved", ""));
        super.addValue(130, new Value("Reserved", ""));
        super.addValue(131, new Value("Reserved", ""));
        super.addValue(132, new Value("Reserved", ""));
        super.addValue(133, new Value("Reserved", ""));
        super.addValue(134, new Value("Reserved", ""));
        super.addValue(135, new Value("Reserved", ""));
        super.addValue(136, new Value("Reserved", ""));
        super.addValue(137, new Value("Reserved", ""));
        super.addValue(138, new Value("Reserved", ""));
        super.addValue(139, new Value("Reserved", ""));
        super.addValue(140, new Value("Reserved", ""));
        super.addValue(141, new Value("Reserved", ""));
        super.addValue(142, new Value("Reserved", ""));
        super.addValue(143, new Value("Reserved", ""));
        super.addValue(144, new Value("Reserved", ""));
        super.addValue(145, new Value("Reserved", ""));
        super.addValue(146, new Value("Reserved", ""));
        super.addValue(147, new Value("Reserved", ""));
        super.addValue(148, new Value("Reserved", ""));
        super.addValue(149, new Value("Reserved", ""));
        super.addValue(150, new Value("Reserved", ""));
        super.addValue(151, new Value("Reserved", ""));
        super.addValue(152, new Value("Reserved", ""));
        super.addValue(153, new Value("Reserved", ""));
        super.addValue(154, new Value("Reserved", ""));
        super.addValue(155, new Value("Reserved", ""));
        super.addValue(156, new Value("Reserved", ""));
        super.addValue(157, new Value("Reserved", ""));
        super.addValue(158, new Value("Reserved", ""));
        super.addValue(159, new Value("Reserved", ""));
        super.addValue(160, new Value("Reserved", ""));
        super.addValue(161, new Value("Reserved", ""));
        super.addValue(162, new Value("Reserved", ""));
        super.addValue(163, new Value("Reserved", ""));
        super.addValue(164, new Value("Reserved", ""));
        super.addValue(165, new Value("Reserved", ""));
        super.addValue(166, new Value("Reserved", ""));
        super.addValue(167, new Value("Reserved", ""));
        super.addValue(168, new Value("Reserved", ""));
        super.addValue(169, new Value("Reserved", ""));
        super.addValue(170, new Value("Reserved", ""));
        super.addValue(171, new Value("Reserved", ""));
        super.addValue(172, new Value("Reserved", ""));
        super.addValue(173, new Value("Reserved", ""));
        super.addValue(174, new Value("Reserved", ""));
        super.addValue(175, new Value("Reserved", ""));
        super.addValue(176, new Value("Reserved", ""));
        super.addValue(177, new Value("Reserved", ""));
        super.addValue(178, new Value("Reserved", ""));
        super.addValue(179, new Value("Reserved", ""));
        super.addValue(180, new Value("Reserved", ""));
        super.addValue(181, new Value("Reserved", ""));
        super.addValue(182, new Value("Reserved", ""));
        super.addValue(183, new Value("Reserved", ""));
        super.addValue(184, new Value("Reserved", ""));
        super.addValue(185, new Value("Reserved", ""));
        super.addValue(186, new Value("Reserved", ""));
        super.addValue(187, new Value("Reserved", ""));
        super.addValue(188, new Value("Reserved", ""));
        super.addValue(189, new Value("Reserved", ""));
        super.addValue(190, new Value("Reserved", ""));
        super.addValue(191, new Value("Reserved", ""));
        super.addValue(192, new Value("Reserved", ""));
        super.addValue(193, new Value("Reserved", ""));
        super.addValue(194, new Value("Reserved", ""));
        super.addValue(195, new Value("Reserved", ""));
        super.addValue(196, new Value("Reserved", ""));
        super.addValue(197, new Value("Reserved", ""));
        super.addValue(198, new Value("Reserved", ""));
        super.addValue(199, new Value("Reserved", ""));
        super.addValue(200, new Value("Reserved", ""));
        super.addValue(201, new Value("Reserved", ""));
        super.addValue(202, new Value("Reserved", ""));
        super.addValue(203, new Value("Reserved", ""));
        super.addValue(204, new Value("Reserved", ""));
        super.addValue(205, new Value("Reserved", ""));
        super.addValue(206, new Value("Reserved", ""));
        super.addValue(207, new Value("Reserved", ""));
        super.addValue(208, new Value("Reserved", ""));
        super.addValue(209, new Value("Reserved", ""));
        super.addValue(210, new Value("Reserved", ""));
        super.addValue(211, new Value("Reserved", ""));
        super.addValue(212, new Value("Reserved", ""));
        super.addValue(213, new Value("Reserved", ""));
        super.addValue(214, new Value("Reserved", ""));
        super.addValue(215, new Value("Reserved", ""));
        super.addValue(216, new Value("Reserved", ""));
        super.addValue(217, new Value("Reserved", ""));
        super.addValue(218, new Value("Reserved", ""));
        super.addValue(219, new Value("Reserved", ""));
        super.addValue(220, new Value("Reserved", ""));
        super.addValue(221, new Value("Reserved", ""));
        super.addValue(222, new Value("Reserved", ""));
        super.addValue(223, new Value("Reserved", ""));
        super.addValue(224, new Value("Reserved", ""));
        super.addValue(225, new Value("Reserved", ""));
        super.addValue(226, new Value("Reserved", ""));
        super.addValue(227, new Value("Reserved", ""));
        super.addValue(228, new Value("Reserved", ""));
        super.addValue(229, new Value("Reserved", ""));
        super.addValue(230, new Value("Reserved", ""));
        super.addValue(231, new Value("Reserved", ""));
        super.addValue(232, new Value("Reserved", ""));
        super.addValue(233, new Value("Reserved", ""));
        super.addValue(234, new Value("Reserved", ""));
        super.addValue(235, new Value("Reserved", ""));
        super.addValue(236, new Value("Reserved", ""));
        super.addValue(237, new Value("Reserved", ""));
        super.addValue(238, new Value("Reserved", ""));
        super.addValue(239, new Value("Reserved", ""));
        super.addValue(240, new Value("Reserved", ""));
        super.addValue(241, new Value("Reserved", ""));
        super.addValue(242, new Value("Reserved", ""));
        super.addValue(243, new Value("Reserved", ""));
        super.addValue(244, new Value("Reserved", ""));
        super.addValue(245, new Value("Reserved", ""));
        super.addValue(246, new Value("Reserved", ""));
        super.addValue(247, new Value("Reserved", ""));
        super.addValue(248, new Value("Reserved", ""));
        super.addValue(249, new Value("Reserved", ""));
        super.addValue(250, new Value("Reserved", ""));
        super.addValue(251, new Value("Reserved", ""));
        super.addValue(252, new Value("Reserved", ""));
        super.addValue(253, new Value("RFC3692-style Experiment 1 (also improperly used for shipping", ""));
        super.addValue(254, new Value("RFC3692-style Experiment 2 (also improperly used for shipping", ""));




    }
}
