package ch1mp.bahdulator.protocols.fields;

import ch1mp.bahdulator.protocols.Value;
import ch1mp.bahdulator.protocols.ProtocolField;

/**
 * The container for UDP Well Known Ports
 *
 * Reference: IANA.org
 *
 * @author Samuel J. Brookes (sjb-ch1mp)
 *
 */
public class UDPSystemPorts extends ProtocolField {

    public UDPSystemPorts(){
        super("udp.system_ports");

        super.addValue(0, new Value("Reserved", ""));
        super.addValue(1, new Value("tcpmux", "TCP Port Service Multiplexer"));
        super.addValue(2, new Value("compressnet", "Management Utility"));
        super.addValue(3, new Value("compressnet", "Compression Process"));
        super.addValue(4, new Value("Unassigned", ""));
        super.addValue(5, new Value("rje", "Remote Job Entry"));
        super.addValue(6, new Value("Unassigned", ""));
        super.addValue(7, new Value("echo", "Echo"));
        super.addValue(8, new Value("Unassigned", ""));
        super.addValue(9, new Value("discard", "Discard"));
        super.addValue(10, new Value("Unassigned", ""));
        super.addValue(11, new Value("systat", "Active Users"));
        super.addValue(12, new Value("Unassigned", ""));
        super.addValue(13, new Value("daytime", "Daytime"));
        super.addValue(14, new Value("Unassigned", ""));
        super.addValue(15, new Value("Unassigned", ""));
        super.addValue(16, new Value("Unassigned", ""));
        super.addValue(17, new Value("qotd", "Quote of the Day"));
        super.addValue(18, new Value("msp", "Message Send Protocol (historic)"));
        super.addValue(19, new Value("chargen", "Character Generator"));
        super.addValue(20, new Value("ftp-data", "File Transfer [Default Data]"));
        super.addValue(21, new Value("ftp", "File Transfer Protocol [Control]"));
        super.addValue(22, new Value("ssh", "The Secure Shell (SSH) Protocol"));
        super.addValue(23, new Value("telnet", "Telnet"));
        super.addValue(24, new Value("any private mail system", ""));
        super.addValue(25, new Value("smtp", "Simple Mail Transfer"));
        super.addValue(26, new Value("Unassigned", ""));
        super.addValue(27, new Value("nsw-fe", "NSW User System FE"));
        super.addValue(28, new Value("Unassigned", ""));
        super.addValue(29, new Value("msg-icp", "MSG ICP"));
        super.addValue(30, new Value("Unassigned", ""));
        super.addValue(31, new Value("msg-auth", "MSG Authentication"));
        super.addValue(32, new Value("Unassigned", ""));
        super.addValue(33, new Value("dsp", "Display Support Protocol"));
        super.addValue(34, new Value("Unassigned", ""));
        super.addValue(35, new Value("any private printer server", ""));
        super.addValue(36, new Value("Unassigned", ""));
        super.addValue(37, new Value("time", "Time"));
        super.addValue(38, new Value("rap", "Route Access Protocol"));
        super.addValue(39, new Value("rlp", "Resource Location Protocol"));
        super.addValue(40, new Value("Unassigned", ""));
        super.addValue(41, new Value("graphics", "Graphics"));
        super.addValue(42, new Value("name", "Host Name Server"));
        super.addValue(42, new Value("nameserver", "Host Name Server"));
        super.addValue(43, new Value("nicname", "Who Is"));
        super.addValue(44, new Value("mpm-flags", "MPM FLAGS Protocol"));
        super.addValue(45, new Value("mpm", "Message Processing Module [recv]"));
        super.addValue(46, new Value("mpm-snd", "MPM [default send]"));
        super.addValue(47, new Value("Reserved", ""));
        super.addValue(48, new Value("auditd", "Digital Audit Daemon"));
        super.addValue(49, new Value("tacacs", "Login Host Protocol (TACACS)"));
        super.addValue(50, new Value("re-mail-ck", "Remote Mail Checking Protocol"));
        super.addValue(52, new Value("xns-time", "XNS Time Protocol"));
        super.addValue(53, new Value("domain", "Domain Name Server"));
        super.addValue(54, new Value("xns-ch", "XNS Clearinghouse"));
        super.addValue(55, new Value("isi-gl", "ISI Graphics Language"));
        super.addValue(56, new Value("xns-auth", "XNS Authentication"));
        super.addValue(57, new Value("any private terminal access", ""));
        super.addValue(58, new Value("xns-mail", "XNS Mail"));
        super.addValue(59, new Value("any private file service", ""));
        super.addValue(60, new Value("Unassigned", ""));
        super.addValue(61, new Value("Reserved", ""));
        super.addValue(62, new Value("acas", "ACA Services"));
        super.addValue(63, new Value("whoispp", "whois++"));
        super.addValue(63, new Value("whois++", "whois++"));
        super.addValue(64, new Value("covia", "Communications Integrator (CI)"));
        super.addValue(65, new Value("tacacs-ds", "TACACS-Database Service"));
        super.addValue(66, new Value("sql-net", "Oracle SQL*NET"));
        super.addValue(66, new Value("sql*net", "Oracle SQL*NET"));
        super.addValue(67, new Value("bootps", "Bootstrap Protocol Server"));
        super.addValue(68, new Value("bootpc", "Bootstrap Protocol Client"));
        super.addValue(69, new Value("tftp", "Trivial File Transfer"));
        super.addValue(70, new Value("gopher", "Gopher"));
        super.addValue(71, new Value("netrjs-1", "Remote Job Service"));
        super.addValue(72, new Value("netrjs-2", "Remote Job Service"));
        super.addValue(73, new Value("netrjs-3", "Remote Job Service"));
        super.addValue(74, new Value("netrjs-4", "Remote Job Service"));
        super.addValue(75, new Value("any private dial out service", ""));
        super.addValue(76, new Value("deos", "Distributed External Object Store"));
        super.addValue(77, new Value("any private RJE service", ""));
        super.addValue(78, new Value("vettcp", "vettcp"));
        super.addValue(79, new Value("finger", "Finger"));
        super.addValue(80, new Value("http", "World Wide Web HTTP"));
        super.addValue(80, new Value("www", "World Wide Web HTTP"));
        super.addValue(80, new Value("www-http", "World Wide Web HTTP"));
        super.addValue(82, new Value("xfer", "XFER Utility"));
        super.addValue(83, new Value("mit-ml-dev", "MIT ML Device"));
        super.addValue(84, new Value("ctf", "Common Trace Facility"));
        super.addValue(85, new Value("mit-ml-dev", "MIT ML Device"));
        super.addValue(86, new Value("mfcobol", "Micro Focus Cobol"));
        super.addValue(87, new Value("any private terminal link", ""));
        super.addValue(88, new Value("kerberos", "Kerberos"));
        super.addValue(89, new Value("su-mit-tg", "SU/MIT Telnet Gateway"));
        super.addValue(90, new Value("dnsix", "DNSIX Securit Attribute Token Map"));
        super.addValue(91, new Value("mit-dov", "MIT Dover Spooler"));
        super.addValue(92, new Value("npp", "Network Printing Protocol"));
        super.addValue(93, new Value("dcp", "Device Control Protocol"));
        super.addValue(94, new Value("objcall", "Tivoli Object Dispatcher"));
        super.addValue(95, new Value("supdup", "SUPDUP"));
        super.addValue(96, new Value("dixie", "DIXIE Protocol Specification"));
        super.addValue(97, new Value("swift-rvf", "Swift Remote Virtural File Protocol"));
        super.addValue(98, new Value("tacnews", "TAC News"));
        super.addValue(99, new Value("metagram", "Metagram Relay"));
        super.addValue(101, new Value("hostname", "NIC Host Name Server"));
        super.addValue(102, new Value("iso-tsap", "ISO-TSAP Class 0"));
        super.addValue(103, new Value("gppitnp", "Genesis Point-to-Point Trans Net"));
        super.addValue(104, new Value("acr-nema", "ACR-NEMA Digital Imag. & Comm. 300"));
        super.addValue(105, new Value("cso", "CCSO name server protocol"));
        super.addValue(105, new Value("csnet-ns", "Mailbox Name Nameserver"));
        super.addValue(106, new Value("3com-tsmux", "3COM-TSMUX"));
        super.addValue(107, new Value("rtelnet", "Remote Telnet Service"));
        super.addValue(108, new Value("snagas", "SNA Gateway Access Server"));
        super.addValue(109, new Value("pop2", "Post Office Protocol - Version 2"));
        super.addValue(110, new Value("pop3", "Post Office Protocol - Version 3"));
        super.addValue(111, new Value("sunrpc", "SUN Remote Procedure Call"));
        super.addValue(112, new Value("mcidas", "McIDAS Data Transmission Protocol"));
        super.addValue(113, new Value("auth", "Authentication Service"));
        super.addValue(115, new Value("sftp", "Simple File Transfer Protocol"));
        super.addValue(116, new Value("ansanotify", "ANSA REX Notify"));
        super.addValue(117, new Value("uucp-path", "UUCP Path Service"));
        super.addValue(118, new Value("sqlserv", "SQL Services"));
        super.addValue(119, new Value("nntp", "Network News Transfer Protocol"));
        super.addValue(120, new Value("cfdptkt", "CFDPTKT"));
        super.addValue(121, new Value("erpc", "Encore Expedited Remote Pro.Call"));
        super.addValue(122, new Value("smakynet", "SMAKYNET"));
        super.addValue(123, new Value("ntp", "Network Time Protocol"));
        super.addValue(124, new Value("ansatrader", "ANSA REX Trader"));
        super.addValue(125, new Value("locus-map", "Locus PC-Interface Net Map Ser"));
        super.addValue(126, new Value("nxedit", "NXEdit"));
        super.addValue(127, new Value("locus-con", "Locus PC-Interface Conn Server"));
        super.addValue(128, new Value("gss-xlicen", "GSS X License Verification"));
        super.addValue(129, new Value("pwdgen", "Password Generator Protocol"));
        super.addValue(130, new Value("cisco-fna", "cisco FNATIVE"));
        super.addValue(131, new Value("cisco-tna", "cisco TNATIVE"));
        super.addValue(132, new Value("cisco-sys", "cisco SYSMAINT"));
        super.addValue(133, new Value("statsrv", "Statistics Service"));
        super.addValue(134, new Value("ingres-net", "INGRES-NET Service"));
        super.addValue(135, new Value("epmap", "DCE endpoint resolution"));
        super.addValue(136, new Value("profile", "PROFILE Naming System"));
        super.addValue(137, new Value("netbios-ns", "NETBIOS Name Service"));
        super.addValue(138, new Value("netbios-dgm", "NETBIOS Datagram Service"));
        super.addValue(139, new Value("netbios-ssn", "NETBIOS Session Service"));
        super.addValue(140, new Value("emfis-data", "EMFIS Data Service"));
        super.addValue(141, new Value("emfis-cntl", "EMFIS Control Service"));
        super.addValue(142, new Value("bl-idm", "Britton-Lee IDM"));
        super.addValue(143, new Value("imap", "Internet Message Access Protocol"));
        super.addValue(144, new Value("uma", "Universal Management Architecture"));
        super.addValue(145, new Value("uaac", "UAAC Protocol"));
        super.addValue(146, new Value("iso-tp0", "ISO-IP0"));
        super.addValue(147, new Value("iso-ip", "ISO-IP"));
        super.addValue(148, new Value("jargon", "Jargon"));
        super.addValue(149, new Value("aed-512", "AED 512 Emulation Service"));
        super.addValue(150, new Value("sql-net", "SQL-NET"));
        super.addValue(151, new Value("hems", "HEMS"));
        super.addValue(152, new Value("bftp", "Background File Transfer Program"));
        super.addValue(153, new Value("sgmp", "SGMP"));
        super.addValue(154, new Value("netsc-prod", "NETSC"));
        super.addValue(155, new Value("netsc-dev", "NETSC"));
        super.addValue(156, new Value("sqlsrv", "SQL Service"));
        super.addValue(157, new Value("knet-cmp", "KNET/VM Command/Message Protocol"));
        super.addValue(158, new Value("pcmail-srv", "PCMail Server"));
        super.addValue(159, new Value("nss-routing", "NSS-Routing"));
        super.addValue(160, new Value("sgmp-traps", "SGMP-TRAPS"));
        super.addValue(161, new Value("snmp", "SNMP"));
        super.addValue(162, new Value("snmptrap", "SNMPTRAP"));
        super.addValue(163, new Value("cmip-man", "CMIP/TCP Manager"));
        super.addValue(164, new Value("cmip-agent", "CMIP/TCP Agent"));
        super.addValue(165, new Value("xns-courier", "Xerox"));
        super.addValue(166, new Value("s-net", "Sirius Systems"));
        super.addValue(167, new Value("namp", "NAMP"));
        super.addValue(168, new Value("rsvd", "RSVD"));
        super.addValue(169, new Value("send", "SEND"));
        super.addValue(170, new Value("print-srv", "Network PostScript"));
        super.addValue(171, new Value("multiplex", "Network Innovations Multiplex"));
        super.addValue(172, new Value("cl-1", "Network Innovations CL/1"));
        super.addValue(172, new Value("cl/1", "Network Innovations CL/1"));
        super.addValue(173, new Value("xyplex-mux", "Xyplex"));
        super.addValue(174, new Value("mailq", "MAILQ"));
        super.addValue(175, new Value("vmnet", "VMNET"));
        super.addValue(176, new Value("genrad-mux", "GENRAD-MUX"));
        super.addValue(177, new Value("xdmcp", "X Display Manager Control Protocol"));
        super.addValue(178, new Value("nextstep", "NextStep Window Server"));
        super.addValue(179, new Value("bgp", "Border Gateway Protocol"));
        super.addValue(180, new Value("ris", "Intergraph"));
        super.addValue(181, new Value("unify", "Unify"));
        super.addValue(182, new Value("audit", "Unisys Audit SITP"));
        super.addValue(183, new Value("ocbinder", "OCBinder"));
        super.addValue(184, new Value("ocserver", "OCServer"));
        super.addValue(185, new Value("remote-kis", "Remote-KIS"));
        super.addValue(186, new Value("kis", "KIS Protocol"));
        super.addValue(187, new Value("aci", "Application Communication Interface"));
        super.addValue(188, new Value("mumps", "Plus Five's MUMPS"));
        super.addValue(189, new Value("qft", "Queued File Transport"));
        super.addValue(190, new Value("gacp", "Gateway Access Control Protocol"));
        super.addValue(191, new Value("prospero", "Prospero Directory Service"));
        super.addValue(192, new Value("osu-nms", "OSU Network Monitoring System"));
        super.addValue(193, new Value("srmp", "Spider Remote Monitoring Protocol"));
        super.addValue(194, new Value("irc", "Internet Relay Chat Protocol"));
        super.addValue(195, new Value("dn6-nlm-aud", "DNSIX Network Level Module Audit"));
        super.addValue(196, new Value("dn6-smm-red", "DNSIX Session Mgt Module Audit Redir"));
        super.addValue(197, new Value("dls", "Directory Location Service"));
        super.addValue(198, new Value("dls-mon", "Directory Location Service Monitor"));
        super.addValue(199, new Value("smux", "SMUX"));
        super.addValue(200, new Value("src", "IBM System Resource Controller"));
        super.addValue(201, new Value("at-rtmp", "AppleTalk Routing Maintenance"));
        super.addValue(202, new Value("at-nbp", "AppleTalk Name Binding"));
        super.addValue(203, new Value("at-3", "AppleTalk Unused"));
        super.addValue(204, new Value("at-echo", "AppleTalk Echo"));
        super.addValue(205, new Value("at-5", "AppleTalk Unused"));
        super.addValue(206, new Value("at-zis", "AppleTalk Zone Information"));
        super.addValue(207, new Value("at-7", "AppleTalk Unused"));
        super.addValue(208, new Value("at-8", "AppleTalk Unused"));
        super.addValue(209, new Value("qmtp", "The Quick Mail Transfer Protocol"));
        super.addValue(210, new Value("z39-50", "ANSI Z39.50"));
        super.addValue(210, new Value("z39.50", "ANSI Z39.50"));
        super.addValue(211, new Value("914c-g", "Texas Instruments 914C/G Terminal"));
        super.addValue(211, new Value("914c/g", "Texas Instruments 914C/G Terminal"));
        super.addValue(212, new Value("anet", "ATEXSSTR"));
        super.addValue(213, new Value("ipx", "IPX"));
        super.addValue(214, new Value("vmpwscs", "VM PWSCS"));
        super.addValue(215, new Value("softpc", "Insignia Solutions"));
        super.addValue(216, new Value("CAIlic", "Computer Associates Int'l License Server"));
        super.addValue(217, new Value("dbase", "dBASE Unix"));
        super.addValue(218, new Value("mpp", "Netix Message Posting Protocol"));
        super.addValue(219, new Value("uarps", "Unisys ARPs"));
        super.addValue(220, new Value("imap3", "Interactive Mail Access Protocol v3"));
        super.addValue(221, new Value("fln-spx", "Berkeley rlogind with SPX auth"));
        super.addValue(222, new Value("rsh-spx", "Berkeley rshd with SPX auth"));
        super.addValue(223, new Value("cdc", "Certificate Distribution Center"));
        super.addValue(224, new Value("masqdialer", "masqdialer"));
        super.addValue(242, new Value("direct", "Direct"));
        super.addValue(243, new Value("sur-meas", "Survey Measurement"));
        super.addValue(244, new Value("inbusiness", "inbusiness"));
        super.addValue(245, new Value("link", "LINK"));
        super.addValue(246, new Value("dsp3270", "Display Systems Protocol"));
        super.addValue(247, new Value("subntbcst-tftp", "SUBNTBCST_TFTP"));
        super.addValue(247, new Value("subntbcst_tftp", "SUBNTBCST_TFTP"));
        super.addValue(248, new Value("bhfhs", "bhfhs"));
        super.addValue(256, new Value("rap", "RAP"));
        super.addValue(257, new Value("set", "Secure Electronic Transaction"));
        super.addValue(259, new Value("esro-gen", "Efficient Short Remote Operations"));
        super.addValue(260, new Value("openport", "Openport"));
        super.addValue(261, new Value("nsiiops", "IIOP Name Service over TLS/SSL"));
        super.addValue(262, new Value("arcisdms", "Arcisdms"));
        super.addValue(263, new Value("hdap", "HDAP"));
        super.addValue(264, new Value("bgmp", "BGMP"));
        super.addValue(265, new Value("x-bone-ctl", "X-Bone CTL"));
        super.addValue(266, new Value("sst", "SCSI on ST"));
        super.addValue(267, new Value("td-service", "Tobit David Service Layer"));
        super.addValue(268, new Value("td-replica", "Tobit David Replica"));
        super.addValue(269, new Value("manet", "MANET Protocols"));
        super.addValue(270, new Value("gist", "Q-mode encapsulation for GIST messages"));
        super.addValue(271, new Value("Reserved", ""));
        super.addValue(280, new Value("http-mgmt", "http-mgmt"));
        super.addValue(281, new Value("personal-link", "Personal Link"));
        super.addValue(282, new Value("cableport-ax", "Cable Port A/X"));
        super.addValue(283, new Value("rescap", "rescap"));
        super.addValue(284, new Value("corerjd", "corerjd"));
        super.addValue(286, new Value("fxp", "FXP Communication"));
        super.addValue(287, new Value("k-block", "K-BLOCK"));
        super.addValue(308, new Value("novastorbakcup", "Novastor Backup"));
        super.addValue(309, new Value("entrusttime", "EntrustTime"));
        super.addValue(310, new Value("bhmds", "bhmds"));
        super.addValue(311, new Value("asip-webadmin", "AppleShare IP WebAdmin"));
        super.addValue(312, new Value("vslmp", "VSLMP"));
        super.addValue(313, new Value("magenta-logic", "Magenta Logic"));
        super.addValue(314, new Value("opalis-robot", "Opalis Robot"));
        super.addValue(315, new Value("dpsi", "DPSI"));
        super.addValue(316, new Value("decauth", "decAuth"));
        super.addValue(317, new Value("zannet", "Zannet"));
        super.addValue(318, new Value("pkix-timestamp", "PKIX TimeStamp"));
        super.addValue(319, new Value("ptp-event", "PTP Event"));
        super.addValue(320, new Value("ptp-general", "PTP General"));
        super.addValue(321, new Value("pip", "PIP"));
        super.addValue(322, new Value("rtsps", "RTSPS"));
        super.addValue(323, new Value("Reserved", ""));
        super.addValue(324, new Value("Reserved", ""));
        super.addValue(333, new Value("texar", "Texar Security Port"));
        super.addValue(344, new Value("pdap", "Prospero Data Access Protocol"));
        super.addValue(345, new Value("pawserv", "Perf Analysis Workbench"));
        super.addValue(346, new Value("zserv", "Zebra server"));
        super.addValue(347, new Value("fatserv", "Fatmen Server"));
        super.addValue(348, new Value("csi-sgwp", "Cabletron Management Protocol"));
        super.addValue(349, new Value("mftp", "mftp"));
        super.addValue(350, new Value("matip-type-a", "MATIP Type A"));
        super.addValue(351, new Value("matip-type-b", "MATIP Type B"));
        super.addValue(351, new Value("bhoetty", "bhoetty"));
        super.addValue(352, new Value("dtag-ste-sb", "DTAG"));
        super.addValue(352, new Value("bhoedap4", "bhoedap4"));
        super.addValue(353, new Value("ndsauth", "NDSAUTH"));
        super.addValue(354, new Value("bh611", "bh611"));
        super.addValue(355, new Value("datex-asn", "DATEX-ASN"));
        super.addValue(356, new Value("cloanto-net-1", "Cloanto Net 1"));
        super.addValue(357, new Value("bhevent", "bhevent"));
        super.addValue(358, new Value("shrinkwrap", "Shrinkwrap"));
        super.addValue(359, new Value("nsrmp", "Network Security Risk Management Protocol"));
        super.addValue(360, new Value("scoi2odialog", "scoi2odialog"));
        super.addValue(361, new Value("semantix", "Semantix"));
        super.addValue(362, new Value("srssend", "SRS Send"));
        super.addValue(363, new Value("rsvp-tunnel", "RSVP Tunnel"));
        super.addValue(363, new Value("rsvp_tunnel", "RSVP Tunnel"));
        super.addValue(364, new Value("aurora-cmgr", "Aurora CMGR"));
        super.addValue(365, new Value("dtk", "DTK"));
        super.addValue(366, new Value("odmr", "ODMR"));
        super.addValue(367, new Value("mortgageware", "MortgageWare"));
        super.addValue(368, new Value("qbikgdp", "QbikGDP"));
        super.addValue(369, new Value("rpc2portmap", "rpc2portmap"));
        super.addValue(370, new Value("codaauth2", "codaauth2"));
        super.addValue(371, new Value("clearcase", "Clearcase"));
        super.addValue(372, new Value("ulistproc", "ListProcessor"));
        super.addValue(373, new Value("legent-1", "Legent Corporation"));
        super.addValue(374, new Value("legent-2", "Legent Corporation"));
        super.addValue(375, new Value("hassle", "Hassle"));
        super.addValue(376, new Value("nip", "Amiga Envoy Network Inquiry Proto"));
        super.addValue(377, new Value("tnETOS", "NEC Corporation"));
        super.addValue(378, new Value("dsETOS", "NEC Corporation"));
        super.addValue(379, new Value("is99c", "TIA/EIA/IS-99 modem client"));
        super.addValue(380, new Value("is99s", "TIA/EIA/IS-99 modem server"));
        super.addValue(381, new Value("hp-collector", "hp performance data collector"));
        super.addValue(382, new Value("hp-managed-node", "hp performance data managed node"));
        super.addValue(383, new Value("hp-alarm-mgr", "hp performance data alarm manager"));
        super.addValue(384, new Value("arns", "A Remote Network Server System"));
        super.addValue(385, new Value("ibm-app", "IBM Application"));
        super.addValue(386, new Value("asa", "ASA Message Router Object Def."));
        super.addValue(387, new Value("aurp", "Appletalk Update-Based Routing Pro."));
        super.addValue(388, new Value("unidata-ldm", "Unidata LDM"));
        super.addValue(389, new Value("ldap", "Lightweight Directory Access Protocol"));
        super.addValue(390, new Value("uis", "UIS"));
        super.addValue(391, new Value("synotics-relay", "SynOptics SNMP Relay Port"));
        super.addValue(392, new Value("synotics-broker", "SynOptics Port Broker Port"));
        super.addValue(393, new Value("meta5", "Meta5"));
        super.addValue(394, new Value("embl-ndt", "EMBL Nucleic Data Transfer"));
        super.addValue(395, new Value("netcp", "NetScout Control Protocol"));
        super.addValue(396, new Value("netware-ip", "Novell Netware over IP"));
        super.addValue(397, new Value("mptn", "Multi Protocol Trans. Net."));
        super.addValue(398, new Value("kryptolan", "Kryptolan"));
        super.addValue(399, new Value("iso-tsap-c2", "ISO Transport Class 2 Non-Control over UDP"));
        super.addValue(400, new Value("osb-sd", "Oracle Secure Backup"));
        super.addValue(401, new Value("ups", "Uninterruptible Power Supply"));
        super.addValue(402, new Value("genie", "Genie Protocol"));
        super.addValue(403, new Value("decap", "decap"));
        super.addValue(404, new Value("nced", "nced"));
        super.addValue(405, new Value("ncld", "ncld"));
        super.addValue(406, new Value("imsp", "Interactive Mail Support Protocol"));
        super.addValue(407, new Value("timbuktu", "Timbuktu"));
        super.addValue(408, new Value("prm-sm", "Prospero Resource Manager Sys. Man."));
        super.addValue(409, new Value("prm-nm", "Prospero Resource Manager Node Man."));
        super.addValue(410, new Value("decladebug", "DECLadebug Remote Debug Protocol"));
        super.addValue(411, new Value("rmt", "Remote MT Protocol"));
        super.addValue(412, new Value("synoptics-trap", "Trap Convention Port"));
        super.addValue(413, new Value("smsp", "Storage Management Services Protocol"));
        super.addValue(414, new Value("infoseek", "InfoSeek"));
        super.addValue(415, new Value("bnet", "BNet"));
        super.addValue(416, new Value("silverplatter", "Silverplatter"));
        super.addValue(417, new Value("onmux", "Onmux"));
        super.addValue(418, new Value("hyper-g", "Hyper-G"));
        super.addValue(419, new Value("ariel1", "Ariel 1"));
        super.addValue(420, new Value("smpte", "SMPTE"));
        super.addValue(421, new Value("ariel2", "Ariel 2"));
        super.addValue(422, new Value("ariel3", "Ariel 3"));
        super.addValue(423, new Value("opc-job-start", "IBM Operations Planning and Control Start"));
        super.addValue(424, new Value("opc-job-track", "IBM Operations Planning and Control Track"));
        super.addValue(425, new Value("icad-el", "ICAD"));
        super.addValue(426, new Value("smartsdp", "smartsdp"));
        super.addValue(427, new Value("svrloc", "Server Location"));
        super.addValue(428, new Value("ocs-cmu", "OCS_CMU"));
        super.addValue(428, new Value("ocs_cmu", "OCS_CMU"));
        super.addValue(429, new Value("ocs-amu", "OCS_AMU"));
        super.addValue(429, new Value("ocs_amu", "OCS_AMU"));
        super.addValue(430, new Value("utmpsd", "UTMPSD"));
        super.addValue(431, new Value("utmpcd", "UTMPCD"));
        super.addValue(432, new Value("iasd", "IASD"));
        super.addValue(433, new Value("nnsp", "NNTP for transit servers (NNSP)"));
        super.addValue(434, new Value("mobileip-agent", "MobileIP-Agent"));
        super.addValue(435, new Value("mobilip-mn", "MobilIP-MN"));
        super.addValue(436, new Value("dna-cml", "DNA-CML"));
        super.addValue(437, new Value("comscm", "comscm"));
        super.addValue(438, new Value("dsfgw", "dsfgw"));
        super.addValue(439, new Value("dasp", "dasp"));
        super.addValue(440, new Value("sgcp", "sgcp"));
        super.addValue(441, new Value("decvms-sysmgt", "decvms-sysmgt"));
        super.addValue(442, new Value("cvc-hostd", "cvc_hostd"));
        super.addValue(442, new Value("cvc_hostd", "cvc_hostd"));
        super.addValue(443, new Value("https", "http protocol over TLS/SSL"));
        super.addValue(444, new Value("snpp", "Simple Network Paging Protocol"));
        super.addValue(445, new Value("microsoft-ds", "Microsoft-DS"));
        super.addValue(446, new Value("ddm-rdb", "DDM-Remote Relational Database Access"));
        super.addValue(447, new Value("ddm-dfm", "DDM-Distributed File Management"));
        super.addValue(448, new Value("ddm-ssl", "DDM-Remote DB Access Using Secure Sockets"));
        super.addValue(449, new Value("as-servermap", "AS Server Mapper"));
        super.addValue(450, new Value("tserver", "Computer Supported Telecomunication Applications"));
        super.addValue(451, new Value("sfs-smp-net", "Cray Network Semaphore server"));
        super.addValue(452, new Value("sfs-config", "Cray SFS config server"));
        super.addValue(453, new Value("creativeserver", "CreativeServer"));
        super.addValue(454, new Value("contentserver", "ContentServer"));
        super.addValue(455, new Value("creativepartnr", "CreativePartnr"));
        super.addValue(456, new Value("macon-udp", "macon-udp"));
        super.addValue(457, new Value("scohelp", "scohelp"));
        super.addValue(458, new Value("appleqtc", "apple quick time"));
        super.addValue(459, new Value("ampr-rcmd", "ampr-rcmd"));
        super.addValue(460, new Value("skronk", "skronk"));
        super.addValue(461, new Value("datasurfsrv", "DataRampSrv"));
        super.addValue(462, new Value("datasurfsrvsec", "DataRampSrvSec"));
        super.addValue(463, new Value("alpes", "alpes"));
        super.addValue(464, new Value("kpasswd", "kpasswd"));
        super.addValue(465, new Value("igmpv3lite", "IGMP over UDP for SSM"));
        super.addValue(466, new Value("digital-vrc", "digital-vrc"));
        super.addValue(467, new Value("mylex-mapd", "mylex-mapd"));
        super.addValue(468, new Value("photuris", "proturis"));
        super.addValue(469, new Value("rcp", "Radio Control Protocol"));
        super.addValue(470, new Value("scx-proxy", "scx-proxy"));
        super.addValue(471, new Value("mondex", "Mondex"));
        super.addValue(472, new Value("ljk-login", "ljk-login"));
        super.addValue(473, new Value("hybrid-pop", "hybrid-pop"));
        super.addValue(474, new Value("tn-tl-w2", "tn-tl-w2"));
        super.addValue(475, new Value("tcpnethaspsrv", "tcpnethaspsrv"));
        super.addValue(476, new Value("tn-tl-fd1", "tn-tl-fd1"));
        super.addValue(477, new Value("ss7ns", "ss7ns"));
        super.addValue(478, new Value("spsc", "spsc"));
        super.addValue(479, new Value("iafserver", "iafserver"));
        super.addValue(480, new Value("iafdbase", "iafdbase"));
        super.addValue(481, new Value("ph", "Ph service"));
        super.addValue(482, new Value("bgs-nsi", "bgs-nsi"));
        super.addValue(483, new Value("ulpnet", "ulpnet"));
        super.addValue(484, new Value("integra-sme", "Integra Software Management Environment"));
        super.addValue(485, new Value("powerburst", "Air Soft Power Burst"));
        super.addValue(486, new Value("avian", "avian"));
        super.addValue(487, new Value("saft", "saft Simple Asynchronous File Transfer"));
        super.addValue(488, new Value("gss-http", "gss-http"));
        super.addValue(489, new Value("nest-protocol", "nest-protocol"));
        super.addValue(490, new Value("micom-pfs", "micom-pfs"));
        super.addValue(491, new Value("go-login", "go-login"));
        super.addValue(492, new Value("ticf-1", "Transport Independent Convergence for FNA"));
        super.addValue(493, new Value("ticf-2", "Transport Independent Convergence for FNA"));
        super.addValue(494, new Value("pov-ray", "POV-Ray"));
        super.addValue(495, new Value("intecourier", "intecourier"));
        super.addValue(496, new Value("pim-rp-disc", "PIM-RP-DISC"));
        super.addValue(497, new Value("retrospect", "Retrospect backup and restore service"));
        super.addValue(498, new Value("siam", "siam"));
        super.addValue(499, new Value("iso-ill", "ISO ILL Protocol"));
        super.addValue(500, new Value("isakmp", "isakmp"));
        super.addValue(501, new Value("stmf", "STMF"));
        super.addValue(502, new Value("mbap", "Modbus Application Protocol"));
        super.addValue(503, new Value("intrinsa", "Intrinsa"));
        super.addValue(504, new Value("citadel", "citadel"));
        super.addValue(505, new Value("mailbox-lm", "mailbox-lm"));
        super.addValue(506, new Value("ohimsrv", "ohimsrv"));
        super.addValue(507, new Value("crs", "crs"));
        super.addValue(508, new Value("xvttp", "xvttp"));
        super.addValue(509, new Value("snare", "snare"));
        super.addValue(510, new Value("fcp", "FirstClass Protocol"));
        super.addValue(511, new Value("passgo", "PassGo"));
        super.addValue(512, new Value("comsat", "comsat"));
        super.addValue(512, new Value("biff", "used by mail system to notify users of new mail received; currently receives messages only from processes on the same machine"));
        super.addValue(513, new Value("who", "maintains data bases showing who's logged in to machines on a local net and the load average of the machine"));
        super.addValue(514, new Value("syslog", "syslog"));
        super.addValue(515, new Value("printer", "spooler"));
        super.addValue(516, new Value("videotex", "videotex"));
        super.addValue(517, new Value("talk", "doesn't use link protocol (this is actually just a rendezvous port from which a tcp connection is established)"));
        super.addValue(518, new Value("ntalk", "ntalk"));
        super.addValue(519, new Value("utime", "unixtime"));
        super.addValue(520, new Value("router", "local routing process (on site); uses variant of Xerox NS routing information protocol - RIP"));
        super.addValue(521, new Value("ripng", "ripng"));
        super.addValue(522, new Value("ulp", "ULP"));
        super.addValue(523, new Value("ibm-db2", "IBM-DB2"));
        super.addValue(524, new Value("ncp", "NCP"));
        super.addValue(525, new Value("timed", "timeserver"));
        super.addValue(526, new Value("tempo", "newdate"));
        super.addValue(527, new Value("stx", "Stock IXChange"));
        super.addValue(528, new Value("custix", "Customer IXChange"));
        super.addValue(529, new Value("irc-serv", "IRC-SERV"));
        super.addValue(530, new Value("courier", "rpc"));
        super.addValue(531, new Value("conference", "chat"));
        super.addValue(532, new Value("netnews", "readnews"));
        super.addValue(533, new Value("netwall", "for emergency broadcasts"));
        super.addValue(534, new Value("windream", "windream Admin"));
        super.addValue(535, new Value("iiop", "iiop"));
        super.addValue(536, new Value("opalis-rdv", "opalis-rdv"));
        super.addValue(537, new Value("nmsp", "Networked Media Streaming Protocol"));
        super.addValue(538, new Value("gdomap", "gdomap"));
        super.addValue(539, new Value("apertus-ldp", "Apertus Technologies Load Determination"));
        super.addValue(540, new Value("uucp", "uucpd"));
        super.addValue(541, new Value("uucp-rlogin", "uucp-rlogin"));
        super.addValue(542, new Value("commerce", "commerce"));
        super.addValue(543, new Value("klogin", "klogin"));
        super.addValue(544, new Value("kshell", "krcmd"));
        super.addValue(545, new Value("appleqtcsrvr", "appleqtcsrvr"));
        super.addValue(546, new Value("dhcpv6-client", "DHCPv6 Client"));
        super.addValue(547, new Value("dhcpv6-server", "DHCPv6 Server"));
        super.addValue(548, new Value("afpovertcp", "AFP over TCP"));
        super.addValue(549, new Value("idfp", "IDFP"));
        super.addValue(550, new Value("new-rwho", "new-who"));
        super.addValue(551, new Value("cybercash", "cybercash"));
        super.addValue(552, new Value("devshr-nts", "DeviceShare"));
        super.addValue(553, new Value("pirp", "pirp"));
        super.addValue(554, new Value("rtsp", "Real Time Streaming Protocol (RTSP)"));
        super.addValue(555, new Value("dsf", "dsf"));
        super.addValue(556, new Value("remotefs", "rfs server"));
        super.addValue(557, new Value("openvms-sysipc", "openvms-sysipc"));
        super.addValue(558, new Value("sdnskmp", "SDNSKMP"));
        super.addValue(559, new Value("teedtap", "TEEDTAP"));
        super.addValue(560, new Value("rmonitor", "rmonitord"));
        super.addValue(561, new Value("monitor", "monitor"));
        super.addValue(562, new Value("chshell", "chcmd"));
        super.addValue(563, new Value("nntps", "nntp protocol over TLS/SSL (was snntp)"));
        super.addValue(564, new Value("9pfs", "plan 9 file service"));
        super.addValue(565, new Value("whoami", "whoami"));
        super.addValue(566, new Value("streettalk", "streettalk"));
        super.addValue(567, new Value("banyan-rpc", "banyan-rpc"));
        super.addValue(568, new Value("ms-shuttle", "microsoft shuttle"));
        super.addValue(569, new Value("ms-rome", "microsoft rome"));
        super.addValue(570, new Value("meter", "demon"));
        super.addValue(571, new Value("meter", "udemon"));
        super.addValue(572, new Value("sonar", "sonar"));
        super.addValue(573, new Value("banyan-vip", "banyan-vip"));
        super.addValue(574, new Value("ftp-agent", "FTP Software Agent System"));
        super.addValue(575, new Value("vemmi", "VEMMI"));
        super.addValue(576, new Value("ipcd", "ipcd"));
        super.addValue(577, new Value("vnas", "vnas"));
        super.addValue(578, new Value("ipdd", "ipdd"));
        super.addValue(579, new Value("decbsrv", "decbsrv"));
        super.addValue(580, new Value("sntp-heartbeat", "SNTP HEARTBEAT"));
        super.addValue(581, new Value("bdp", "Bundle Discovery Protocol"));
        super.addValue(582, new Value("scc-security", "SCC Security"));
        super.addValue(583, new Value("philips-vc", "Philips Video-Conferencing"));
        super.addValue(584, new Value("keyserver", "Key Server"));
        super.addValue(586, new Value("password-chg", "Password Change"));
        super.addValue(587, new Value("submission", "Message Submission"));
        super.addValue(588, new Value("cal", "CAL"));
        super.addValue(589, new Value("eyelink", "EyeLink"));
        super.addValue(590, new Value("tns-cml", "TNS CML"));
        super.addValue(591, new Value("http-alt", "Inc. - HTTP Alternate (see Port 80)"));
        super.addValue(592, new Value("eudora-set", "Eudora Set"));
        super.addValue(593, new Value("http-rpc-epmap", "HTTP RPC Ep Map"));
        super.addValue(594, new Value("tpip", "TPIP"));
        super.addValue(595, new Value("cab-protocol", "CAB Protocol"));
        super.addValue(596, new Value("smsd", "SMSD"));
        super.addValue(597, new Value("ptcnameservice", "PTC Name Service"));
        super.addValue(598, new Value("sco-websrvrmg3", "SCO Web Server Manager 3"));
        super.addValue(599, new Value("acp", "Aeolon Core Protocol"));
        super.addValue(600, new Value("ipcserver", "Sun IPC server"));
        super.addValue(601, new Value("syslog-conn", "Reliable Syslog Service"));
        super.addValue(602, new Value("xmlrpc-beep", "XML-RPC over BEEP"));
        super.addValue(603, new Value("idxp", "IDXP"));
        super.addValue(604, new Value("tunnel", "TUNNEL"));
        super.addValue(605, new Value("soap-beep", "SOAP over BEEP"));
        super.addValue(606, new Value("urm", "Cray Unified Resource Manager"));
        super.addValue(607, new Value("nqs", "nqs"));
        super.addValue(608, new Value("sift-uft", "Sender-Initiated/Unsolicited File Transfer"));
        super.addValue(609, new Value("npmp-trap", "npmp-trap"));
        super.addValue(610, new Value("npmp-local", "npmp-local"));
        super.addValue(611, new Value("npmp-gui", "npmp-gui"));
        super.addValue(612, new Value("hmmp-ind", "HMMP Indication"));
        super.addValue(613, new Value("hmmp-op", "HMMP Operation"));
        super.addValue(614, new Value("sshell", "SSLshell"));
        super.addValue(615, new Value("sco-inetmgr", "Internet Configuration Manager"));
        super.addValue(616, new Value("sco-sysmgr", "SCO System Administration Server"));
        super.addValue(617, new Value("sco-dtmgr", "SCO Desktop Administration Server"));
        super.addValue(618, new Value("dei-icda", "DEI-ICDA"));
        super.addValue(619, new Value("compaq-evm", "Compaq EVM"));
        super.addValue(620, new Value("sco-websrvrmgr", "SCO WebServer Manager"));
        super.addValue(621, new Value("escp-ip", "ESCP"));
        super.addValue(622, new Value("collaborator", "Collaborator"));
        super.addValue(623, new Value("asf-rmcp", "ASF Remote Management and Control Protocol"));
        super.addValue(624, new Value("cryptoadmin", "Crypto Admin"));
        super.addValue(625, new Value("dec-dlm", "DEC DLM"));
        super.addValue(625, new Value("dec_dlm", "DEC DLM"));
        super.addValue(626, new Value("asia", "ASIA"));
        super.addValue(627, new Value("passgo-tivoli", "PassGo Tivoli"));
        super.addValue(628, new Value("qmqp", "QMQP"));
        super.addValue(629, new Value("3com-amp3", "3Com AMP3"));
        super.addValue(630, new Value("rda", "RDA"));
        super.addValue(631, new Value("ipp", "IPP (Internet Printing Protocol)"));
        super.addValue(632, new Value("bmpp", "bmpp"));
        super.addValue(633, new Value("servstat", "Service Status update (Sterling Software)"));
        super.addValue(634, new Value("ginad", "ginad"));
        super.addValue(635, new Value("rlzdbase", "RLZ DBase"));
        super.addValue(636, new Value("ldaps", "ldap protocol over TLS/SSL (was sldap)"));
        super.addValue(637, new Value("lanserver", "lanserver"));
        super.addValue(638, new Value("mcns-sec", "mcns-sec"));
        super.addValue(639, new Value("msdp", "MSDP"));
        super.addValue(640, new Value("entrust-sps", "entrust-sps"));
        super.addValue(641, new Value("repcmd", "repcmd"));
        super.addValue(642, new Value("esro-emsdp", "ESRO-EMSDP V1.3"));
        super.addValue(643, new Value("sanity", "SANity"));
        super.addValue(644, new Value("dwr", "dwr"));
        super.addValue(645, new Value("pssc", "PSSC"));
        super.addValue(646, new Value("ldp", "LDP"));
        super.addValue(647, new Value("dhcp-failover", "DHCP Failover"));
        super.addValue(648, new Value("rrp", "Registry Registrar Protocol (RRP)"));
        super.addValue(649, new Value("cadview-3d", "Cadview-3d - streaming 3d models over the internet"));
        super.addValue(650, new Value("obex", "OBEX"));
        super.addValue(651, new Value("ieee-mms", "IEEE MMS"));
        super.addValue(652, new Value("hello-port", "HELLO_PORT"));
        super.addValue(653, new Value("repscmd", "RepCmd"));
        super.addValue(654, new Value("aodv", "AODV"));
        super.addValue(655, new Value("tinc", "TINC"));
        super.addValue(656, new Value("spmp", "SPMP"));
        super.addValue(657, new Value("rmc", "RMC"));
        super.addValue(658, new Value("tenfold", "TenFold"));
        super.addValue(660, new Value("mac-srvr-admin", "MacOS Server Admin"));
        super.addValue(661, new Value("hap", "HAP"));
        super.addValue(662, new Value("pftp", "PFTP"));
        super.addValue(663, new Value("purenoise", "PureNoise"));
        super.addValue(664, new Value("asf-secure-rmcp", "ASF Secure Remote Management and Control Protocol"));
        super.addValue(665, new Value("sun-dr", "Sun DR"));
        super.addValue(666, new Value("mdqs", "mdqs"));
        super.addValue(666, new Value("doom", "doom Id Software"));
        super.addValue(667, new Value("disclose", "campaign contribution disclosures - SDR Technologies"));
        super.addValue(668, new Value("mecomm", "MeComm"));
        super.addValue(669, new Value("meregister", "MeRegister"));
        super.addValue(670, new Value("vacdsm-sws", "VACDSM-SWS"));
        super.addValue(671, new Value("vacdsm-app", "VACDSM-APP"));
        super.addValue(672, new Value("vpps-qua", "VPPS-QUA"));
        super.addValue(673, new Value("cimplex", "CIMPLEX"));
        super.addValue(674, new Value("acap", "ACAP"));
        super.addValue(675, new Value("dctp", "DCTP"));
        super.addValue(676, new Value("vpps-via", "VPPS Via"));
        super.addValue(677, new Value("vpp", "Virtual Presence Protocol"));
        super.addValue(678, new Value("ggf-ncp", "GNU Generation Foundation NCP"));
        super.addValue(679, new Value("mrm", "MRM"));
        super.addValue(680, new Value("entrust-aaas", "entrust-aaas"));
        super.addValue(681, new Value("entrust-aams", "entrust-aams"));
        super.addValue(682, new Value("xfr", "XFR"));
        super.addValue(683, new Value("corba-iiop", "CORBA IIOP"));
        super.addValue(684, new Value("corba-iiop-ssl", "CORBA IIOP SSL"));
        super.addValue(685, new Value("mdc-portmapper", "MDC Port Mapper"));
        super.addValue(686, new Value("hcp-wismar", "Hardware Control Protocol Wismar"));
        super.addValue(687, new Value("asipregistry", "asipregistry"));
        super.addValue(688, new Value("realm-rusd", "ApplianceWare managment protocol"));
        super.addValue(689, new Value("nmap", "NMAP"));
        super.addValue(690, new Value("vatp", "Velneo Application Transfer Protocol"));
        super.addValue(691, new Value("msexch-routing", "MS Exchange Routing"));
        super.addValue(692, new Value("hyperwave-isp", "Hyperwave-ISP"));
        super.addValue(693, new Value("connendp", "almanid Connection Endpoint"));
        super.addValue(694, new Value("ha-cluster", "ha-cluster"));
        super.addValue(695, new Value("ieee-mms-ssl", "IEEE-MMS-SSL"));
        super.addValue(696, new Value("rushd", "RUSHD"));
        super.addValue(697, new Value("uuidgen", "UUIDGEN"));
        super.addValue(698, new Value("olsr", "OLSR"));
        super.addValue(699, new Value("accessnetwork", "Access Network"));
        super.addValue(700, new Value("epp", "Extensible Provisioning Protocol"));
        super.addValue(701, new Value("lmp", "Link Management Protocol (LMP)"));
        super.addValue(702, new Value("iris-beep", "IRIS over BEEP"));
        super.addValue(704, new Value("elcsd", "errlog copy/server daemon"));
        super.addValue(705, new Value("agentx", "AgentX"));
        super.addValue(706, new Value("silc", "SILC"));
        super.addValue(707, new Value("borland-dsj", "Borland DSJ"));
        super.addValue(709, new Value("entrust-kmsh", "Entrust Key Management Service Handler"));
        super.addValue(710, new Value("entrust-ash", "Entrust Administration Service Handler"));
        super.addValue(711, new Value("cisco-tdp", "Cisco TDP"));
        super.addValue(712, new Value("tbrpf", "TBRPF"));
        super.addValue(713, new Value("iris-xpc", "IRIS over XPC"));
        super.addValue(714, new Value("iris-xpcs", "IRIS over XPCS"));
        super.addValue(715, new Value("iris-lwz", "IRIS-LWZ"));
        super.addValue(716, new Value("pana", "PANA Messages"));
        super.addValue(729, new Value("netviewdm1", "IBM NetView DM/6000 Server/Client"));
        super.addValue(730, new Value("netviewdm2", "IBM NetView DM/6000 send/tcp"));
        super.addValue(731, new Value("netviewdm3", "IBM NetView DM/6000 receive/tcp"));
        super.addValue(741, new Value("netgw", "netGW"));
        super.addValue(742, new Value("netrcs", "Network based Rev. Cont. Sys."));
        super.addValue(744, new Value("flexlm", "Flexible License Manager"));
        super.addValue(747, new Value("fujitsu-dev", "Fujitsu Device Control"));
        super.addValue(748, new Value("ris-cm", "Russell Info Sci Calendar Manager"));
        super.addValue(749, new Value("kerberos-adm", "kerberos administration"));
        super.addValue(750, new Value("loadav", "loadav"));
        super.addValue(750, new Value("kerberos-iv", "kerberos version iv"));
        super.addValue(751, new Value("pump", "pump"));
        super.addValue(752, new Value("qrh", "qrh"));
        super.addValue(753, new Value("rrh", "rrh"));
        super.addValue(754, new Value("tell", "send"));
        super.addValue(758, new Value("nlogin", "nlogin"));
        super.addValue(759, new Value("con", "con"));
        super.addValue(760, new Value("ns", "ns"));
        super.addValue(761, new Value("rxe", "rxe"));
        super.addValue(762, new Value("quotad", "quotad"));
        super.addValue(763, new Value("cycleserv", "cycleserv"));
        super.addValue(764, new Value("omserv", "omserv"));
        super.addValue(765, new Value("webster", "webster"));
        super.addValue(767, new Value("phonebook", "phone"));
        super.addValue(769, new Value("vid", "vid"));
        super.addValue(770, new Value("cadlock", "cadlock"));
        super.addValue(771, new Value("rtip", "rtip"));
        super.addValue(772, new Value("cycleserv2", "cycleserv2"));
        super.addValue(773, new Value("notify", "notify"));
        super.addValue(774, new Value("acmaint-dbd", "IANA assigned this well-formed service name as a replacement for acmaint_dbd."));
        super.addValue(774, new Value("acmaint_dbd", "acmaint_dbd"));
        super.addValue(775, new Value("acmaint-transd", "IANA assigned this well-formed service name as a replacement for acmaint_transd."));
        super.addValue(775, new Value("acmaint_transd", "acmaint_transd"));
        super.addValue(776, new Value("wpages", "wpages"));
        super.addValue(777, new Value("multiling-http", "Multiling HTTP"));
        super.addValue(780, new Value("wpgs", "wpgs"));
        super.addValue(800, new Value("mdbs-daemon", "IANA assigned this well-formed service name as a replacement for mdbs_daemon."));
        super.addValue(800, new Value("mdbs_daemon", "mdbs_daemon"));
        super.addValue(801, new Value("device", "device"));
        super.addValue(802, new Value("mbap-s", "Modbus Application Protocol Secure"));
        super.addValue(810, new Value("fcp-udp", "FCP Datagram"));
        super.addValue(828, new Value("itm-mcell-s", "itm-mcell-s"));
        super.addValue(829, new Value("pkix-3-ca-ra", "PKIX-3 CA/RA"));
        super.addValue(830, new Value("netconf-ssh", "NETCONF over SSH"));
        super.addValue(831, new Value("netconf-beep", "NETCONF over BEEP"));
        super.addValue(832, new Value("netconfsoaphttp", "NETCONF for SOAP over HTTPS"));
        super.addValue(833, new Value("netconfsoapbeep", "NETCONF for SOAP over BEEP"));
        super.addValue(847, new Value("dhcp-failover2", "dhcp-failover 2"));
        super.addValue(848, new Value("gdoi", "GDOI"));
        super.addValue(853, new Value("domain-s", "DNS query-response protocol run over TLS/DTLS"));
        super.addValue(854, new Value("dlep", "Dynamic Link Exchange Protocol (DLEP)"));
        super.addValue(860, new Value("iscsi", "iSCSI"));
        super.addValue(861, new Value("owamp-test", "OWAMP-Test"));
        super.addValue(862, new Value("twamp-test", "TWAMP-Test Receiver Port"));
        super.addValue(873, new Value("rsync", "rsync"));
        super.addValue(886, new Value("iclcnet-locate", "ICL coNETion locate server"));
        super.addValue(887, new Value("iclcnet-svinfo", "ICL coNETion server info"));
        super.addValue(887, new Value("iclcnet_svinfo", "ICL coNETion server info"));
        super.addValue(888, new Value("accessbuilder", "AccessBuilder"));
        super.addValue(900, new Value("omginitialrefs", "OMG Initial Refs"));
        super.addValue(901, new Value("smpnameres", "SMPNAMERES"));
        super.addValue(902, new Value("ideafarm-door", "self documenting Door: send 0x00 for info"));
        super.addValue(903, new Value("ideafarm-panic", "self documenting Panic Door: send 0x00 for info"));
        super.addValue(910, new Value("kink", "Kerberized Internet Negotiation of Keys (KINK)"));
        super.addValue(911, new Value("xact-backup", "xact-backup"));
        super.addValue(912, new Value("apex-mesh", "APEX relay-relay service"));
        super.addValue(913, new Value("apex-edge", "APEX endpoint-relay service"));
        super.addValue(953, new Value("Reserved", ""));
        super.addValue(989, new Value("ftps-data", "over TLS/SSL"));
        super.addValue(990, new Value("ftps", "over TLS/SSL"));
        super.addValue(991, new Value("nas", "Netnews Administration System"));
        super.addValue(992, new Value("telnets", "telnet protocol over TLS/SSL"));
        super.addValue(993, new Value("imaps", "imap4 protocol over TLS/SSL"));
        super.addValue(994, new Value("Reserved", ""));
        super.addValue(995, new Value("pop3s", "pop3 protocol over TLS/SSL (was spop3)"));
        super.addValue(996, new Value("vsinet", "vsinet"));
        super.addValue(997, new Value("maitrd", "maitrd"));
        super.addValue(998, new Value("puparp", "puparp"));
        super.addValue(999, new Value("applix", "Applix ac"));
        super.addValue(999, new Value("puprouter", "puprouter"));
        super.addValue(1000, new Value("cadlock2", "cadlock2"));
        super.addValue(1001, new Value("Reserved", ""));
        super.addValue(1008, new Value("Possibly used by Sun Solaris????", ""));
        super.addValue(1010, new Value("surf", "surf"));
        super.addValue(1021, new Value("exp1", "RFC3692-style Experiment 1"));
        super.addValue(1022, new Value("exp2", "RFC3692-style Experiment 2"));
        super.addValue(1023, new Value("Reserved", ""));


    }
}
